In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
pyr_four = pd.read_csv('pyr_four_nostr.csv', index_col=[0])

In [5]:
# note: no normalization has been applied
pyr_four

mito_id  mito_vx  ctr_pos_x_vx  ctr_pos_y_vx  ctr_pos_z_vx  \
0       1783325   527936         75186         43844          1430   
1       1780086  1597632         75086         43678          1032   
2       2026719   141924         79378         47892           742   
3       1540216     2780         69738         42838            21   
5       2633343   363328         89636         57886           961   
...         ...      ...           ...           ...           ...   
210970  1649818   287444         72610         37220          2135   
210971  2397704   336092         84174         56050          1975   
210972  1667802   337984         72740         46280          1200   
210973  1654227   495816         72104         39630          1908   
210974  1088579  1012668         61868         43872           755   

        bbox_beg_x_vx  bbox_beg_y_vx  bbox_beg_z_vx  bbox_end_x_vx  \
0               74824          43668           1323          75472   
1               74168          43342            675          76458   
2               79192          47734            738          79532   
3               69708          42816             21          69770   
5               89434          57430            935          89878   
...               ...            ...            ...            ...   
210970          72356          37078           2095          72840   
210971          83712          55254           1936          84612   
210972          72594          45918           1153          72916   
210973          72006          38894           1826          72178   
210974          61088          43396            586          62586   

        bbox_end_y_vx  bbox_end_z_vx              cellid  ctr_pos_x_nm  \
0               44120           1561  648518346349523993        300744   
1               44298           1362  648518346349523993        300344   
2               48034            749  648518346349523993        317512   
3               42862             23  648518346349523993        278952   
5               58520            982  648518346349523993        358544   
...               ...            ...                 ...           ...   
210970          37450           2157  648518346349492130        290440   
210971          56830           1992  648518346349492130        336696   
210972          46642           1248  648518346349492130        290960   
210973          40170           1940  648518346349492130        288416   
210974          44688            925  648518346349492130        247472   

        ctr_pos_y_nm  ctr_pos_z_nm  surface_area  complexityindex compartment  \
0             175376         57200      6.187842        20.482515       Basal   
1             174712         41280     18.720821        61.936882       Basal   
2             191568         29680      1.382960         3.164067       Basal   
3             171352           840      0.044947         0.283093     Somatic   
5             231544         38440      3.868432        10.566605       Basal   
...              ...           ...           ...              ...         ...   
210970        148880         85400      3.736330        15.210989     Somatic   
210971        224200         79000      4.604071        20.817940       Basal   
210972        185120         48000      3.541754         9.371107       Basal   
210973        158520         76320      5.980140        20.961437     Somatic   
210974        175488         30200     12.196261        42.625959       Basal   

        centroid_x  centroid_y  centroid_z  ctr_distance_to_soma  bbox_dir_x  \
0            70864       42368          24           4778.608166        -648   
1            70864       42368          24           4534.032201       -2290   
2            70864       42368          24          10174.394134        -340   
3            70864       42368          24           1220.157777         -62   
5            70864       42368          24          24373.638977

# From Jose Portilla Machine Learning Course (Udemy)

# Train test split

In [6]:
X = pyr_four.drop('compartment',axis=1)
y = pyr_four['compartment']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

# Decision Tree

In [8]:
dtree = DecisionTreeClassifier()

In [9]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [10]:
# removed presort argument which caused an error
dtree.fit(X_train,y_train)
dtree.fit(X_train,y_train)
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

DecisionTreeClassifier()

# Prediction and evaluation 

In [11]:
predictions = dtree.predict(X_test)

In [12]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      Apical       0.78      0.79      0.78      5869
      Axonal       0.73      0.73      0.73      3783
       Basal       0.85      0.84      0.84     16513
     Somatic       0.96      0.96      0.96     28107

    accuracy                           0.89     54272
   macro avg       0.83      0.83      0.83     54272
weighted avg       0.89      0.89      0.89     54272



In [13]:
print(confusion_matrix(y_test,predictions))

[[ 4625    74   940   230]
 [   62  2775   802   144]
 [ 1024   777 13909   803]
 [  222   159   794 26932]]


# Random forests

In [14]:
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [15]:
rfc_pred = rfc.predict(X_test)

In [16]:
print(confusion_matrix(y_test,rfc_pred))

[[ 4656    17   984   212]
 [   44  2944   667   128]
 [  693   440 14715   665]
 [   44    11   338 27714]]


In [17]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

      Apical       0.86      0.79      0.82      5869
      Axonal       0.86      0.78      0.82      3783
       Basal       0.88      0.89      0.89     16513
     Somatic       0.97      0.99      0.98     28107

    accuracy                           0.92     54272
   macro avg       0.89      0.86      0.88     54272
weighted avg       0.92      0.92      0.92     54272



In [18]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

      Apical       0.86      0.79      0.82      5869
      Axonal       0.86      0.78      0.82      3783
       Basal       0.88      0.89      0.89     16513
     Somatic       0.97      0.99      0.98     28107

    accuracy                           0.92     54272
   macro avg       0.89      0.86      0.88     54272
weighted avg       0.92      0.92      0.92     54272



# I thought that I was re-running with the mito to mito stats but I didn't actually update the df name, so it re-ran the analysis again with the original df. However, the results of the running the random forest again now returned very high success rates

In [33]:
# I loaded the new df but forgot to update the df name in the following cell
pyr_four_nostr_mmstats = pd.read_csv('pyr_four_nostr_mmstats.csv', index_col=[0])
pyr_four_nostr_mmstats

mito_id  mito_vx  ctr_pos_x_vx  ctr_pos_y_vx  ctr_pos_z_vx  \
0       1783325   527936         75186         43844          1430   
1       1780086  1597632         75086         43678          1032   
2       2026719   141924         79378         47892           742   
3       1540216     2780         69738         42838            21   
4       2633343   363328         89636         57886           961   
...         ...      ...           ...           ...           ...   
180899  1649818   287444         72610         37220          2135   
180900  2397704   336092         84174         56050          1975   
180901  1667802   337984         72740         46280          1200   
180902  1654227   495816         72104         39630          1908   
180903  1088579  1012668         61868         43872           755   

        bbox_beg_x_vx  bbox_beg_y_vx  bbox_beg_z_vx  bbox_end_x_vx  \
0               74824          43668           1323          75472   
1               74168          43342            675          76458   
2               79192          47734            738          79532   
3               69708          42816             21          69770   
4               89434          57430            935          89878   
...               ...            ...            ...            ...   
180899          72356          37078           2095          72840   
180900          83712          55254           1936          84612   
180901          72594          45918           1153          72916   
180902          72006          38894           1826          72178   
180903          61088          43396            586          62586   

        bbox_end_y_vx  bbox_end_z_vx              cellid  ctr_pos_x_nm  \
0               44120           1561  648518346349523993        300744   
1               44298           1362  648518346349523993        300344   
2               48034            749  648518346349523993        317512   
3               42862             23  648518346349523993        278952   
4               58520            982  648518346349523993        358544   
...               ...            ...                 ...           ...   
180899          37450           2157  648518346349492130        290440   
180900          56830           1992  648518346349492130        336696   
180901          46642           1248  648518346349492130        290960   
180902          40170           1940  648518346349492130        288416   
180903          44688            925  648518346349492130        247472   

        ctr_pos_y_nm  ctr_pos_z_nm  surface_area  complexityindex compartment  \
0             175376         57200      6.187842        20.482515       Basal   
1             174712         41280     18.720821        61.936882       Basal   
2             191568         29680      1.382960         3.164067       Basal   
3             171352           840      0.044947         0.283093     Somatic   
4             231544         38440      3.868432        10.566605       Basal   
...              ...           ...           ...              ...         ...   
180899        148880         85400      3.736330        15.210989     Somatic   
180900        224200         79000      4.604071        20.817940       Basal   
180901        185120         48000      3.541754         9.371107       Basal   
180902        158520         76320      5.980140        20.961437     Somatic   
180903        175488         30200     12.196261        42.625959       Basal   

        centroid_x  centroid_y  centroid_z  ctr_distance_to_soma  bbox_dir_x  \
0            70864       42368          24           4778.608166        -648   
1            70864       42368          24           4534.032201       -2290   
2            70864       42368          24          10174.394134        -340   
3            70864       42368          24           1220.157777         -62   
4            70864       42368          24          24373.638977

# Train test split

In [19]:
# here's where I made the mistake of not updating the df name; it still has the original one
X = pyr_four.drop('compartment',axis=1)
y = pyr_four['compartment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

# Decision tree

In [20]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
dtree.fit(X_train,y_train)
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

DecisionTreeClassifier()

# Predictions and evaluation

In [21]:
predictions = dtree.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      Apical       0.78      0.79      0.78      5921
      Axonal       0.71      0.73      0.72      3678
       Basal       0.84      0.84      0.84     16377
     Somatic       0.96      0.96      0.96     28296

    accuracy                           0.89     54272
   macro avg       0.82      0.83      0.83     54272
weighted avg       0.89      0.89      0.89     54272



In [22]:
print(confusion_matrix(y_test,predictions))

[[ 4664    82   957   218]
 [   67  2668   818   125]
 [ 1016   844 13747   770]
 [  219   166   835 27076]]


# Random forests

# Here's what the difference was: I didn't reset the rfc here. rfc here is using the rfc df from the first run.

# I was supposed to add the following, but missed it, and as a result, rfc was the first run got used when running these cells for the second time

rfc = RandomForestClassifier(n_estimators=100)  
rfc.fit(X_train, y_train)

# If I would have included these lines here, it would have reset rfc to a new state.

In [23]:
rfc_pred = rfc.predict(X_test)
print(confusion_matrix(y_test,rfc_pred))

[[ 5568     5   294    54]
 [    9  3441   189    39]
 [  214   126 15852   185]
 [   15     1   102 28178]]


In [24]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

      Apical       0.96      0.94      0.95      5921
      Axonal       0.96      0.94      0.95      3678
       Basal       0.96      0.97      0.97     16377
     Somatic       0.99      1.00      0.99     28296

    accuracy                           0.98     54272
   macro avg       0.97      0.96      0.96     54272
weighted avg       0.98      0.98      0.98     54272

